// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDirectory() {
  return window['go']['api']['Api']['AddDirectory']();
}

export function AddFiles() {
  return window['go']['api']['Api']['AddFiles']();
}

export function GetData() {
  return window['go']['api']['Api']['GetData']();
}

export function Init(arg1) {
  return window['go']['api']['Api']['Init'](arg1);
}

export function OnFileDrop(arg1, arg2, arg3) {
  return window['go']['api']['Api']['OnFileDrop'](arg1, arg2, arg3);
}
