// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {context} from '../models';

export function AddDirectory():Promise<api.ApiReturnValue>;

export function AddFiles():Promise<api.ApiReturnValue>;

export function GetData():Promise<api.ApiReturnValue>;

export function Init(arg1:context.Context):Promise<void>;

export function OnFileDrop(arg1:number,arg2:number,arg3:Array<string>):Promise<void>;
